server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:file:/data/notification-v01
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
